// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListComments = `-- name: AdminListComments :many
SELECT
    c.id,
    c.post_id,
    p.title AS post_title,
    p.slug AS post_slug,
    c.display_name,
    c.body,
    c.status,
    c.created_at,
    c.moderated_at
FROM comments c
JOIN posts p ON p.id = c.post_id
WHERE $1::comment_status IS NULL
   OR c.status = $1::comment_status
ORDER BY c.created_at DESC
`

type AdminListCommentsRow struct {
	ID          uuid.UUID          `json:"id"`
	PostID      uuid.UUID          `json:"post_id"`
	PostTitle   string             `json:"post_title"`
	PostSlug    string             `json:"post_slug"`
	DisplayName string             `json:"display_name"`
	Body        string             `json:"body"`
	Status      CommentStatus      `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ModeratedAt pgtype.Timestamptz `json:"moderated_at"`
}

func (q *Queries) AdminListComments(ctx context.Context, status NullCommentStatus) ([]AdminListCommentsRow, error) {
	rows, err := q.db.Query(ctx, adminListComments, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCommentsRow{}
	for rows.Next() {
		var i AdminListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.PostTitle,
			&i.PostSlug,
			&i.DisplayName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.ModeratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPendingComment = `-- name: CreatePendingComment :one
INSERT INTO comments (
    post_id,
    display_name,
    body,
    ip_hash,
    user_agent_hash
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, post_id, display_name, body, status, created_at
`

type CreatePendingCommentParams struct {
	PostID        uuid.UUID `json:"post_id"`
	DisplayName   string    `json:"display_name"`
	Body          string    `json:"body"`
	IpHash        string    `json:"ip_hash"`
	UserAgentHash string    `json:"user_agent_hash"`
}

type CreatePendingCommentRow struct {
	ID          uuid.UUID          `json:"id"`
	PostID      uuid.UUID          `json:"post_id"`
	DisplayName string             `json:"display_name"`
	Body        string             `json:"body"`
	Status      CommentStatus      `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePendingComment(ctx context.Context, arg CreatePendingCommentParams) (CreatePendingCommentRow, error) {
	row := q.db.QueryRow(ctx, createPendingComment,
		arg.PostID,
		arg.DisplayName,
		arg.Body,
		arg.IpHash,
		arg.UserAgentHash,
	)
	var i CreatePendingCommentRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.DisplayName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedCommentsForPost = `-- name: ListApprovedCommentsForPost :many
SELECT
    id,
    post_id,
    display_name,
    body,
    status,
    created_at
FROM comments
WHERE post_id = $1
  AND status = 'approved'
ORDER BY created_at ASC
`

type ListApprovedCommentsForPostRow struct {
	ID          uuid.UUID          `json:"id"`
	PostID      uuid.UUID          `json:"post_id"`
	DisplayName string             `json:"display_name"`
	Body        string             `json:"body"`
	Status      CommentStatus      `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListApprovedCommentsForPost(ctx context.Context, postID uuid.UUID) ([]ListApprovedCommentsForPostRow, error) {
	rows, err := q.db.Query(ctx, listApprovedCommentsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedCommentsForPostRow{}
	for rows.Next() {
		var i ListApprovedCommentsForPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.DisplayName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateComment = `-- name: ModerateComment :one
UPDATE comments
SET
    status = $2,
    moderated_at = now()
WHERE id = $1
RETURNING id, post_id, display_name, body, status, ip_hash, user_agent_hash, created_at, moderated_at
`

type ModerateCommentParams struct {
	ID     uuid.UUID     `json:"id"`
	Status CommentStatus `json:"status"`
}

func (q *Queries) ModerateComment(ctx context.Context, arg ModerateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, moderateComment, arg.ID, arg.Status)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.DisplayName,
		&i.Body,
		&i.Status,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
		&i.ModeratedAt,
	)
	return i, err
}
