// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListContactMessages = `-- name: AdminListContactMessages :many
SELECT
    id,
    name,
    email,
    message,
    status,
    created_at
FROM contact_messages
WHERE $1::contact_message_status IS NULL
   OR status = $1::contact_message_status
ORDER BY created_at DESC
`

type AdminListContactMessagesRow struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	Email     string               `json:"email"`
	Message   string               `json:"message"`
	Status    ContactMessageStatus `json:"status"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) AdminListContactMessages(ctx context.Context, status NullContactMessageStatus) ([]AdminListContactMessagesRow, error) {
	rows, err := q.db.Query(ctx, adminListContactMessages, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListContactMessagesRow{}
	for rows.Next() {
		var i AdminListContactMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createContactMessage = `-- name: CreateContactMessage :one
INSERT INTO contact_messages (
    name,
    email,
    message,
    ip_hash,
    user_agent_hash
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, email, message, status, created_at
`

type CreateContactMessageParams struct {
	Name          string `json:"name"`
	Email         string `json:"email"`
	Message       string `json:"message"`
	IpHash        string `json:"ip_hash"`
	UserAgentHash string `json:"user_agent_hash"`
}

type CreateContactMessageRow struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	Email     string               `json:"email"`
	Message   string               `json:"message"`
	Status    ContactMessageStatus `json:"status"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (CreateContactMessageRow, error) {
	row := q.db.QueryRow(ctx, createContactMessage,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.IpHash,
		arg.UserAgentHash,
	)
	var i CreateContactMessageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateContactMessageStatus = `-- name: UpdateContactMessageStatus :one
UPDATE contact_messages
SET status = $2
WHERE id = $1
RETURNING id, name, email, message, status, created_at
`

type UpdateContactMessageStatusParams struct {
	ID     uuid.UUID            `json:"id"`
	Status ContactMessageStatus `json:"status"`
}

type UpdateContactMessageStatusRow struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	Email     string               `json:"email"`
	Message   string               `json:"message"`
	Status    ContactMessageStatus `json:"status"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) UpdateContactMessageStatus(ctx context.Context, arg UpdateContactMessageStatusParams) (UpdateContactMessageStatusRow, error) {
	row := q.db.QueryRow(ctx, updateContactMessageStatus, arg.ID, arg.Status)
	var i UpdateContactMessageStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
