// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListMCPTokens = `-- name: AdminListMCPTokens :many
SELECT id, name, token_hash, scope, created_by, created_at, last_used_at, revoked_at
FROM mcp_tokens
ORDER BY created_at DESC
`

func (q *Queries) AdminListMCPTokens(ctx context.Context) ([]McpToken, error) {
	rows, err := q.db.Query(ctx, adminListMCPTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpToken{}
	for rows.Next() {
		var i McpToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.Scope,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMCPToken = `-- name: CreateMCPToken :one
INSERT INTO mcp_tokens (
    name,
    token_hash,
    scope,
    created_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, token_hash, scope, created_by, created_at, last_used_at, revoked_at
`

type CreateMCPTokenParams struct {
	Name      string        `json:"name"`
	TokenHash string        `json:"token_hash"`
	Scope     McpTokenScope `json:"scope"`
	CreatedBy pgtype.UUID   `json:"created_by"`
}

func (q *Queries) CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, createMCPToken,
		arg.Name,
		arg.TokenHash,
		arg.Scope,
		arg.CreatedBy,
	)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveMCPTokenByHash = `-- name: GetActiveMCPTokenByHash :one
SELECT id, name, token_hash, scope, created_by, created_at, last_used_at, revoked_at
FROM mcp_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveMCPTokenByHash(ctx context.Context, tokenHash string) (McpToken, error) {
	row := q.db.QueryRow(ctx, getActiveMCPTokenByHash, tokenHash)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markMCPTokenUsed = `-- name: MarkMCPTokenUsed :exec
UPDATE mcp_tokens
SET last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) MarkMCPTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMCPTokenUsed, id)
	return err
}

const revokeMCPToken = `-- name: RevokeMCPToken :one
UPDATE mcp_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, name, token_hash, scope, created_by, created_at, last_used_at, revoked_at
`

func (q *Queries) RevokeMCPToken(ctx context.Context, id uuid.UUID) (McpToken, error) {
	row := q.db.QueryRow(ctx, revokeMCPToken, id)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
