// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const adminListMedia = `-- name: AdminListMedia :many
SELECT id, filename, storage_path, mime_type, size_bytes, alt_text, created_at
FROM media
ORDER BY created_at DESC
`

func (q *Queries) AdminListMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.Query(ctx, adminListMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoragePath,
			&i.MimeType,
			&i.SizeBytes,
			&i.AltText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    filename,
    storage_path,
    mime_type,
    size_bytes,
    alt_text
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, filename, storage_path, mime_type, size_bytes, alt_text, created_at
`

type CreateMediaParams struct {
	Filename    string `json:"filename"`
	StoragePath string `json:"storage_path"`
	MimeType    string `json:"mime_type"`
	SizeBytes   int64  `json:"size_bytes"`
	AltText     string `json:"alt_text"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.Filename,
		arg.StoragePath,
		arg.MimeType,
		arg.SizeBytes,
		arg.AltText,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.AltText,
		&i.CreatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, filename, storage_path, mime_type, size_bytes, alt_text, created_at
FROM media
WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoragePath,
		&i.MimeType,
		&i.SizeBytes,
		&i.AltText,
		&i.CreatedAt,
	)
	return i, err
}
