// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CommentStatus string

const (
	CommentStatusPending  CommentStatus = "pending"
	CommentStatusApproved CommentStatus = "approved"
	CommentStatusSpam     CommentStatus = "spam"
	CommentStatusDeleted  CommentStatus = "deleted"
)

func (e *CommentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentStatus(s)
	case string:
		*e = CommentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentStatus: %T", src)
	}
	return nil
}

type NullCommentStatus struct {
	CommentStatus CommentStatus `json:"comment_status"`
	Valid         bool          `json:"valid"` // Valid is true if CommentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentStatus), nil
}

type ContactMessageStatus string

const (
	ContactMessageStatusNew      ContactMessageStatus = "new"
	ContactMessageStatusRead     ContactMessageStatus = "read"
	ContactMessageStatusArchived ContactMessageStatus = "archived"
)

func (e *ContactMessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactMessageStatus(s)
	case string:
		*e = ContactMessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactMessageStatus: %T", src)
	}
	return nil
}

type NullContactMessageStatus struct {
	ContactMessageStatus ContactMessageStatus `json:"contact_message_status"`
	Valid                bool                 `json:"valid"` // Valid is true if ContactMessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContactMessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactMessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactMessageStatus), nil
}

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus `json:"post_status"`
	Valid      bool       `json:"valid"` // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID            uuid.UUID          `json:"id"`
	PostID        uuid.UUID          `json:"post_id"`
	DisplayName   string             `json:"display_name"`
	Body          string             `json:"body"`
	Status        CommentStatus      `json:"status"`
	IpHash        string             `json:"ip_hash"`
	UserAgentHash string             `json:"user_agent_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ModeratedAt   pgtype.Timestamptz `json:"moderated_at"`
}

type ContactMessage struct {
	ID            uuid.UUID            `json:"id"`
	Name          string               `json:"name"`
	Email         string               `json:"email"`
	Message       string               `json:"message"`
	IpHash        string               `json:"ip_hash"`
	UserAgentHash string               `json:"user_agent_hash"`
	Status        ContactMessageStatus `json:"status"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

type Medium struct {
	ID          uuid.UUID          `json:"id"`
	Filename    string             `json:"filename"`
	StoragePath string             `json:"storage_path"`
	MimeType    string             `json:"mime_type"`
	SizeBytes   int64              `json:"size_bytes"`
	AltText     string             `json:"alt_text"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	Title                string             `json:"title"`
	Excerpt              string             `json:"excerpt"`
	ContentMarkdown      string             `json:"content_markdown"`
	ContentHtmlSanitized string             `json:"content_html_sanitized"`
	Status               PostStatus         `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	AuthorID             pgtype.UUID        `json:"author_id"`
	SeoTitle             string             `json:"seo_title"`
	SeoDescription       string             `json:"seo_description"`
	OgImageID            pgtype.UUID        `json:"og_image_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PostTag struct {
	PostID uuid.UUID `json:"post_id"`
	Tag    string    `json:"tag"`
}

type Profile struct {
	ID               int16              `json:"id"`
	FullName         string             `json:"full_name"`
	Headline         string             `json:"headline"`
	ShortBio         string             `json:"short_bio"`
	LongBio          string             `json:"long_bio"`
	Location         string             `json:"location"`
	CurrentCompany   string             `json:"current_company"`
	FocusAreas       []string           `json:"focus_areas"`
	Skills           []string           `json:"skills"`
	GithubUrl        string             `json:"github_url"`
	LinkedinUrl      string             `json:"linkedin_url"`
	Email            string             `json:"email"`
	ProfileImagePath string             `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Eyebrow     string             `json:"eyebrow"`
	Summary     string             `json:"summary"`
	Description string             `json:"description"`
	Problem     string             `json:"problem"`
	Built       string             `json:"built"`
	Signals     []string           `json:"signals"`
	Stack       []string           `json:"stack"`
	RepoUrl     string             `json:"repo_url"`
	DemoUrl     pgtype.Text        `json:"demo_url"`
	SortOrder   int32              `json:"sort_order"`
	IsFeatured  bool               `json:"is_featured"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	TotpSecretEncrypted pgtype.Text        `json:"totp_secret_encrypted"`
	Role                UserRole           `json:"role"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
}
