// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTags = `-- name: AddPostTags :exec
INSERT INTO post_tags (post_id, tag)
SELECT $1, unnest($2::text[])
ON CONFLICT DO NOTHING
`

type AddPostTagsParams struct {
	PostID uuid.UUID `json:"post_id"`
	Tags   []string  `json:"tags"`
}

func (q *Queries) AddPostTags(ctx context.Context, arg AddPostTagsParams) error {
	_, err := q.db.Exec(ctx, addPostTags, arg.PostID, arg.Tags)
	return err
}

const adminGetPost = `-- name: AdminGetPost :one
SELECT
    id,
    slug,
    title,
    excerpt,
    content_markdown,
    content_html_sanitized,
    status,
    published_at,
    author_id,
    seo_title,
    seo_description,
    og_image_id,
    created_at,
    updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) AdminGetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, adminGetPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.ContentHtmlSanitized,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListPosts = `-- name: AdminListPosts :many
SELECT
    id,
    slug,
    title,
    excerpt,
    status,
    published_at,
    seo_title,
    seo_description,
    created_at,
    updated_at
FROM posts
ORDER BY created_at DESC
`

type AdminListPostsRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Excerpt        string             `json:"excerpt"`
	Status         PostStatus         `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	SeoTitle       string             `json:"seo_title"`
	SeoDescription string             `json:"seo_description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AdminListPosts(ctx context.Context) ([]AdminListPostsRow, error) {
	rows, err := q.db.Query(ctx, adminListPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPostsRow{}
	for rows.Next() {
		var i AdminListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Status,
			&i.PublishedAt,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    slug,
    title,
    excerpt,
    content_markdown,
    content_html_sanitized,
    status,
    published_at,
    author_id,
    seo_title,
    seo_description,
    og_image_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, slug, title, excerpt, content_markdown, content_html_sanitized, status, published_at, author_id, seo_title, seo_description, og_image_id, created_at, updated_at
`

type CreatePostParams struct {
	Slug                 string             `json:"slug"`
	Title                string             `json:"title"`
	Excerpt              string             `json:"excerpt"`
	ContentMarkdown      string             `json:"content_markdown"`
	ContentHtmlSanitized string             `json:"content_html_sanitized"`
	Status               PostStatus         `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	AuthorID             pgtype.UUID        `json:"author_id"`
	SeoTitle             string             `json:"seo_title"`
	SeoDescription       string             `json:"seo_description"`
	OgImageID            pgtype.UUID        `json:"og_image_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.ContentHtmlSanitized,
		arg.Status,
		arg.PublishedAt,
		arg.AuthorID,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgImageID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.ContentHtmlSanitized,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deletePostTags = `-- name: DeletePostTags :exec
DELETE FROM post_tags
WHERE post_id = $1
`

func (q *Queries) DeletePostTags(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostTags, postID)
	return err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.content_markdown,
    p.content_html_sanitized,
    p.status,
    p.published_at,
    p.seo_title,
    p.seo_description,
    p.created_at,
    p.updated_at,
    COALESCE(array_agg(pt.tag ORDER BY pt.tag) FILTER (WHERE pt.tag IS NOT NULL), '{}')::text[] AS tags
FROM posts p
LEFT JOIN post_tags pt ON pt.post_id = p.id
WHERE p.slug = $1
  AND p.status = 'published'
GROUP BY p.id
`

type GetPublishedPostBySlugRow struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	Title                string             `json:"title"`
	Excerpt              string             `json:"excerpt"`
	ContentMarkdown      string             `json:"content_markdown"`
	ContentHtmlSanitized string             `json:"content_html_sanitized"`
	Status               PostStatus         `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	SeoTitle             string             `json:"seo_title"`
	SeoDescription       string             `json:"seo_description"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Tags                 []string           `json:"tags"`
}

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, slug string) (GetPublishedPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, slug)
	var i GetPublishedPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.ContentHtmlSanitized,
		&i.Status,
		&i.PublishedAt,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT
    p.id,
    p.slug,
    p.title,
    p.excerpt,
    p.status,
    p.published_at,
    p.seo_title,
    p.seo_description,
    p.created_at,
    p.updated_at,
    COALESCE(array_agg(pt.tag ORDER BY pt.tag) FILTER (WHERE pt.tag IS NOT NULL), '{}')::text[] AS tags
FROM posts p
LEFT JOIN post_tags pt ON pt.post_id = p.id
WHERE p.status = 'published'
GROUP BY p.id
ORDER BY p.published_at DESC
`

type ListPublishedPostsRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Excerpt        string             `json:"excerpt"`
	Status         PostStatus         `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	SeoTitle       string             `json:"seo_title"`
	SeoDescription string             `json:"seo_description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Tags           []string           `json:"tags"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPostsRow{}
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Status,
			&i.PublishedAt,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    slug = $2,
    title = $3,
    excerpt = $4,
    content_markdown = $5,
    content_html_sanitized = $6,
    status = $7,
    published_at = $8,
    seo_title = $9,
    seo_description = $10,
    og_image_id = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, title, excerpt, content_markdown, content_html_sanitized, status, published_at, author_id, seo_title, seo_description, og_image_id, created_at, updated_at
`

type UpdatePostParams struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	Title                string             `json:"title"`
	Excerpt              string             `json:"excerpt"`
	ContentMarkdown      string             `json:"content_markdown"`
	ContentHtmlSanitized string             `json:"content_html_sanitized"`
	Status               PostStatus         `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	SeoTitle             string             `json:"seo_title"`
	SeoDescription       string             `json:"seo_description"`
	OgImageID            pgtype.UUID        `json:"og_image_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.ContentHtmlSanitized,
		arg.Status,
		arg.PublishedAt,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgImageID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.ContentHtmlSanitized,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
