// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"
)

const getProfile = `-- name: GetProfile :one
SELECT
    id,
    full_name,
    headline,
    short_bio,
    long_bio,
    location,
    current_company,
    focus_areas,
    skills,
    github_url,
    linkedin_url,
    email,
    profile_image_path,
    created_at,
    updated_at
FROM profile
WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Headline,
		&i.ShortBio,
		&i.LongBio,
		&i.Location,
		&i.CurrentCompany,
		&i.FocusAreas,
		&i.Skills,
		&i.GithubUrl,
		&i.LinkedinUrl,
		&i.Email,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profile
SET
    full_name = $1,
    headline = $2,
    short_bio = $3,
    long_bio = $4,
    location = $5,
    current_company = $6,
    focus_areas = $7,
    skills = $8,
    github_url = $9,
    linkedin_url = $10,
    email = $11,
    profile_image_path = $12,
    updated_at = now()
WHERE id = 1
RETURNING id, full_name, headline, short_bio, long_bio, location, current_company, focus_areas, skills, github_url, linkedin_url, email, profile_image_path, created_at, updated_at
`

type UpdateProfileParams struct {
	FullName         string   `json:"full_name"`
	Headline         string   `json:"headline"`
	ShortBio         string   `json:"short_bio"`
	LongBio          string   `json:"long_bio"`
	Location         string   `json:"location"`
	CurrentCompany   string   `json:"current_company"`
	FocusAreas       []string `json:"focus_areas"`
	Skills           []string `json:"skills"`
	GithubUrl        string   `json:"github_url"`
	LinkedinUrl      string   `json:"linkedin_url"`
	Email            string   `json:"email"`
	ProfileImagePath string   `json:"profile_image_path"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.FullName,
		arg.Headline,
		arg.ShortBio,
		arg.LongBio,
		arg.Location,
		arg.CurrentCompany,
		arg.FocusAreas,
		arg.Skills,
		arg.GithubUrl,
		arg.LinkedinUrl,
		arg.Email,
		arg.ProfileImagePath,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Headline,
		&i.ShortBio,
		&i.LongBio,
		&i.Location,
		&i.CurrentCompany,
		&i.FocusAreas,
		&i.Skills,
		&i.GithubUrl,
		&i.LinkedinUrl,
		&i.Email,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
