// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListProjects = `-- name: AdminListProjects :many
SELECT
    id,
    slug,
    title,
    eyebrow,
    summary,
    description,
    problem,
    built,
    signals,
    stack,
    repo_url,
    demo_url,
    sort_order,
    is_featured,
    created_at,
    updated_at
FROM projects
ORDER BY sort_order ASC, created_at DESC
`

func (q *Queries) AdminListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, adminListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Eyebrow,
			&i.Summary,
			&i.Description,
			&i.Problem,
			&i.Built,
			&i.Signals,
			&i.Stack,
			&i.RepoUrl,
			&i.DemoUrl,
			&i.SortOrder,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    slug,
    title,
    eyebrow,
    summary,
    description,
    problem,
    built,
    signals,
    stack,
    repo_url,
    demo_url,
    sort_order,
    is_featured
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, slug, title, eyebrow, summary, description, problem, built, signals, stack, repo_url, demo_url, sort_order, is_featured, created_at, updated_at
`

type CreateProjectParams struct {
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Eyebrow     string      `json:"eyebrow"`
	Summary     string      `json:"summary"`
	Description string      `json:"description"`
	Problem     string      `json:"problem"`
	Built       string      `json:"built"`
	Signals     []string    `json:"signals"`
	Stack       []string    `json:"stack"`
	RepoUrl     string      `json:"repo_url"`
	DemoUrl     pgtype.Text `json:"demo_url"`
	SortOrder   int32       `json:"sort_order"`
	IsFeatured  bool        `json:"is_featured"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Title,
		arg.Eyebrow,
		arg.Summary,
		arg.Description,
		arg.Problem,
		arg.Built,
		arg.Signals,
		arg.Stack,
		arg.RepoUrl,
		arg.DemoUrl,
		arg.SortOrder,
		arg.IsFeatured,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Eyebrow,
		&i.Summary,
		&i.Description,
		&i.Problem,
		&i.Built,
		&i.Signals,
		&i.Stack,
		&i.RepoUrl,
		&i.DemoUrl,
		&i.SortOrder,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT
    id,
    slug,
    title,
    eyebrow,
    summary,
    description,
    problem,
    built,
    signals,
    stack,
    repo_url,
    demo_url,
    sort_order,
    is_featured,
    created_at,
    updated_at
FROM projects
WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Eyebrow,
		&i.Summary,
		&i.Description,
		&i.Problem,
		&i.Built,
		&i.Signals,
		&i.Stack,
		&i.RepoUrl,
		&i.DemoUrl,
		&i.SortOrder,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeaturedProjects = `-- name: ListFeaturedProjects :many
SELECT
    id,
    slug,
    title,
    eyebrow,
    summary,
    description,
    problem,
    built,
    signals,
    stack,
    repo_url,
    demo_url,
    sort_order,
    is_featured,
    created_at,
    updated_at
FROM projects
WHERE is_featured = true
ORDER BY sort_order ASC, created_at DESC
`

func (q *Queries) ListFeaturedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listFeaturedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Eyebrow,
			&i.Summary,
			&i.Description,
			&i.Problem,
			&i.Built,
			&i.Signals,
			&i.Stack,
			&i.RepoUrl,
			&i.DemoUrl,
			&i.SortOrder,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    slug = $2,
    title = $3,
    eyebrow = $4,
    summary = $5,
    description = $6,
    problem = $7,
    built = $8,
    signals = $9,
    stack = $10,
    repo_url = $11,
    demo_url = $12,
    sort_order = $13,
    is_featured = $14,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, title, eyebrow, summary, description, problem, built, signals, stack, repo_url, demo_url, sort_order, is_featured, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Eyebrow     string      `json:"eyebrow"`
	Summary     string      `json:"summary"`
	Description string      `json:"description"`
	Problem     string      `json:"problem"`
	Built       string      `json:"built"`
	Signals     []string    `json:"signals"`
	Stack       []string    `json:"stack"`
	RepoUrl     string      `json:"repo_url"`
	DemoUrl     pgtype.Text `json:"demo_url"`
	SortOrder   int32       `json:"sort_order"`
	IsFeatured  bool        `json:"is_featured"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Eyebrow,
		arg.Summary,
		arg.Description,
		arg.Problem,
		arg.Built,
		arg.Signals,
		arg.Stack,
		arg.RepoUrl,
		arg.DemoUrl,
		arg.SortOrder,
		arg.IsFeatured,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Eyebrow,
		&i.Summary,
		&i.Description,
		&i.Problem,
		&i.Built,
		&i.Signals,
		&i.Stack,
		&i.RepoUrl,
		&i.DemoUrl,
		&i.SortOrder,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
