// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminGetPost(ctx context.Context, id uuid.UUID) (Post, error)
	AdminListAuditLog(ctx context.Context, arg AdminListAuditLogParams) ([]AuditLog, error)
	AdminListComments(ctx context.Context, status NullCommentStatus) ([]AdminListCommentsRow, error)
	AdminListContactMessages(ctx context.Context, status NullContactMessageStatus) ([]AdminListContactMessagesRow, error)
	AdminListMedia(ctx context.Context) ([]Medium, error)
	AdminListPosts(ctx context.Context) ([]AdminListPostsRow, error)
	AdminListProjects(ctx context.Context) ([]Project, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (CreateContactMessageRow, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePendingComment(ctx context.Context, arg CreatePendingCommentParams) (CreatePendingCommentRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeletePost(ctx context.Context, id uuid.UUID) error
	GetMedia(ctx context.Context, id uuid.UUID) (Medium, error)
	GetProfile(ctx context.Context) (Profile, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetPublishedPostBySlug(ctx context.Context, slug string) (GetPublishedPostBySlugRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListApprovedCommentsForPost(ctx context.Context, postID uuid.UUID) ([]ListApprovedCommentsForPostRow, error)
	ListFeaturedProjects(ctx context.Context) ([]Project, error)
	ListPublishedPosts(ctx context.Context) ([]ListPublishedPostsRow, error)
	ModerateComment(ctx context.Context, arg ModerateCommentParams) (Comment, error)
	ReplacePostTags(ctx context.Context, arg ReplacePostTagsParams) error
	RevokeSession(ctx context.Context, tokenHash string) error
	UpdateContactMessageStatus(ctx context.Context, arg UpdateContactMessageStatusParams) (UpdateContactMessageStatusRow, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
